name: Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Flask app
      run: |
        export FLASK_APP=WebApp/app.py  # Change to your main Flask file path
        export FLASK_ENV=development
        flask run --host=0.0.0.0
